### ISSUE TITLE
zimme:active-route 2.0.0

### ISSUE THREAD

**Issue by zimme** [VeliovGroup/iron-router-helpers-for-Meteor#2]
Hey

I just wanted to let you know that I've released 2.0.0 of my package `zimme:active-route` (previously `zimme:iron-router-active`).

I now have support for the `{{isActiveRoute 'string'}}` syntax which your package provides.

How do you feel about working together?

**Comment by dr-dimitru** [comment]
@zimme I didn't get why you've decided rename `zimme:iron-router-active` package? It was so successful. Or it's not depend from `iron-router` anymore?
I'm okay to work together, but how we can help to each other? I'm open to any suggestions from your end.

**Comment by zimme** [comment]
I renamed it because the new version also support `meteorhacks:flow-router` =)

**Comment by dr-dimitru** [comment]
Yeah, get into the code and new docs, got it.
BTW how we can help to each other? Currently, yours and mine packages is fulfilled

**Comment by zimme** [comment]
Yeah, I was thinking looking ahead.

Your package is called `iron-router-helpers`, maybe there are some other helpers we can use this package for and keep the isActiveRoute/Path in my package or we might ending up "hiding" this package with `meteor admin set-unmigrated ostrio:iron-router-helpers`.

If you want I could probably add you as a collaborator for my package and we'll just need to find a nice workflow for committing new changes and stuff. I'm thinking anything except patches should be developed in it's own branch and PR for code review before merging new features.

**Comment by dr-dimitru** [comment]
Agree, gitflow is always welcome
Yes, I'll review code later on this wee to make sure backward compatibility of our packages
Then I'll be ready to merge projects

**Comment by dr-dimitru** [comment]
@zimme Could you please create dev branch, wanna to publish some updates, I've got this message:
_You may not have permission to access zimme-meteor-active-route. Check Preferences to make sure you’re still logged in._

**Comment by dr-dimitru** [comment]
@zimme please see [5b8dd877](https://github.com/VeliovGroup/iron-router-helpers-for-Meteor/commit/5b8dd877f4d7d311d8b13c141ffb935942d79d34) commit

**Comment by zimme** [comment]
I don't really see the need to have a `devel` branch for [active-route](https://github.com/zimme/meteor-active-route), I always try and work out of new branches except for some smaller patches.

Either you could just fork my project, do the changes you want and open a PR and we'll discuss the changes in that PR until we're satisfied and we merge them. Or I'll add you as a collaborator and you create a new branch for the changes you want to make, do the changes in that branch and open a PR and we'll discuss the changes in there until we're satisfied and we merge the changes.

**Comment by zimme** [comment]
Also I use [Autopublish](https://autopublish.meteor.com) for publishing my package, I just do my changes, merge PR's and create a tag and autopublish publishes the package for me.

**Comment by zimme** [comment]
For the changes to your package stating that you're deprecating the package in favor of mine, you shouldn't need either access to my github repo or have to be a maintainer of my meteor package, right?

**Comment by dr-dimitru** [comment]
@zimme you need to decide, to give me permission to create branches and let me develop inside your repo (you can keep PR merging on your end), or to work via PRs from my side.
BTW, do you want to let me send PR right into master?

**Comment by zimme** [comment]
How about we start with you working from you own fork of my project and once we see one or two successful PR's I'll give you access?

Is this ok with you?

**Comment by zimme** [comment]
and yes, we branch from `master` and we merge back into `master`

**Comment by dr-dimitru** [comment]
Cause we have non-compatible differences in our packages, merging of our packages is not possible

**Comment by zimme** [comment]
So if I were to add an option to do regex matching for the for {{isActiveRoute 'regex'}}, would this maybe be enough? because then the default would be string matching and setting `ActiveRoute.config({regex: true});` would make it do regex matching instead.

What do you think about this approach?
